on:
  push:
    branches:
      - main
    paths:
      - '**.php'
      - 'phpunit.xml'
      - '!measure/**'

env:
  NODE_VERSION: '16.x'
  PHP_VERSION: '7.4'
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  CI:
    name: Continuous Integration
    # refs. https://github.com/actions/virtual-environments/tree/main/images/linux
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          extensions: bcmath, gmp
          ini-values: memory_limit=-1
          tools: pecl, composer
          coverage: none

      - name: tools version
        run: |
          php -v
          composer -V

      - name: composer install
        shell: bash
        run: composer install --prefer-dist --no-progress

      - name: phpunit
        shell: bash
        run: php ./vendor/bin/phpunit

      #-- Slack通知 --#
      # 成功
      - name: succeeded phpunit
        if: ${{ success() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_TITLE: ':sunny: succeeded phpunit'
          SLACK_COLOR: ${{ job.status }}
          MSG_MINIMAL: Actions URL,Commit
          SLACK_ICON: https://www.masterpiece.co.jp/wp-content/themes/mp/img/mp_logo.png

      # 失敗
      - name: failed to phpunit
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_TITLE: ':umbrella_with_rain_drops: failed to phpunit'
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://www.masterpiece.co.jp/wp-content/themes/mp/img/mp_logo.png
